#!/bin/bash

# SPDX-FileCopyrightText: 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

python3 recorder.py -a $1 -p $2 -s \
Vehicle.ADAS.ABS.IsEnabled \
Vehicle.ADAS.ABS.IsEngaged \
Vehicle.ADAS.ABS.IsError \
Vehicle.ADAS.ActiveAutonomyLevel \
Vehicle.ADAS.CruiseControl.IsActive \
Vehicle.ADAS.CruiseControl.IsClutchSwitchPressed \
Vehicle.ADAS.CruiseControl.IsEnabled \
Vehicle.ADAS.CruiseControl.IsError \
Vehicle.ADAS.CruiseControl.IsPowerTakeOffOn \
Vehicle.ADAS.CruiseControl.SpeedSet \
Vehicle.ADAS.EBA.IsEnabled \
Vehicle.ADAS.EBA.IsEngaged \
Vehicle.ADAS.EBA.IsError \
Vehicle.ADAS.EBD.IsEnabled \
Vehicle.ADAS.EBD.IsEngaged \
Vehicle.ADAS.EBD.IsError \
Vehicle.ADAS.ESC.IsEnabled \
Vehicle.ADAS.ESC.IsEngaged \
Vehicle.ADAS.ESC.IsError \
Vehicle.ADAS.ESC.IsStrongCrossWindDetected \
Vehicle.ADAS.ESC.RoadFriction.LowerBound \
Vehicle.ADAS.ESC.RoadFriction.MostProbable \
Vehicle.ADAS.ESC.RoadFriction.UpperBound \
Vehicle.ADAS.LaneDepartureDetection.IsEnabled \
Vehicle.ADAS.LaneDepartureDetection.IsError \
Vehicle.ADAS.LaneDepartureDetection.IsWarning \
Vehicle.ADAS.ObstacleDetection.IsEnabled \
Vehicle.ADAS.ObstacleDetection.IsError \
Vehicle.ADAS.ObstacleDetection.IsWarning \
Vehicle.ADAS.PowerOptimizeLevel \
Vehicle.ADAS.SupportedAutonomyLevel \
Vehicle.ADAS.TCS.IsEnabled \
Vehicle.ADAS.TCS.IsEngaged \
Vehicle.ADAS.TCS.IsError \
Vehicle.Acceleration.Lateral \
Vehicle.Acceleration.Longitudinal \
Vehicle.Acceleration.Vertical \
Vehicle.AngularVelocity.Pitch \
Vehicle.AngularVelocity.Roll \
Vehicle.AngularVelocity.Yaw \
Vehicle.AverageSpeed \
Vehicle.Body.BodyType \
Vehicle.Body.Hood.IsOpen \
Vehicle.Body.Horn.IsActive \
Vehicle.Body.Lights.Backup.IsDefect \
Vehicle.Body.Lights.Backup.IsOn \
Vehicle.Body.Lights.Beam.High.IsDefect \
Vehicle.Body.Lights.Beam.High.IsOn \
Vehicle.Body.Lights.Beam.Low.IsDefect \
Vehicle.Body.Lights.Beam.Low.IsOn \
Vehicle.Body.Lights.Brake.IsActive \
Vehicle.Body.Lights.Brake.IsDefect \
Vehicle.Body.Lights.DirectionIndicator.Left.IsDefect \
Vehicle.Body.Lights.DirectionIndicator.Left.IsSignaling \
Vehicle.Body.Lights.DirectionIndicator.Right.IsDefect \
Vehicle.Body.Lights.DirectionIndicator.Right.IsSignaling \
Vehicle.Body.Lights.Fog.Front.IsDefect \
Vehicle.Body.Lights.Fog.Front.IsOn \
Vehicle.Body.Lights.Fog.Rear.IsDefect \
Vehicle.Body.Lights.Fog.Rear.IsOn \
Vehicle.Body.Lights.Hazard.IsDefect \
Vehicle.Body.Lights.Hazard.IsSignaling \
Vehicle.Body.Lights.IsHighBeamSwitchOn \
Vehicle.Body.Lights.LicensePlate.IsDefect \
Vehicle.Body.Lights.LicensePlate.IsOn \
Vehicle.Body.Lights.LightSwitch \
Vehicle.Body.Lights.Parking.IsDefect \
Vehicle.Body.Lights.Parking.IsOn \
Vehicle.Body.Lights.Running.IsDefect \
Vehicle.Body.Lights.Running.IsOn \
Vehicle.Body.Mirrors.Left.IsHeatingOn \
Vehicle.Body.Mirrors.Left.Pan \
Vehicle.Body.Mirrors.Left.Tilt \
Vehicle.Body.Mirrors.Right.IsHeatingOn \
Vehicle.Body.Mirrors.Right.Pan \
Vehicle.Body.Mirrors.Right.Tilt \
Vehicle.Body.PowerOptimizeLevel \
Vehicle.Body.Raindetection.Intensity \
Vehicle.Body.RearMainSpoilerPosition \
Vehicle.Body.RefuelPosition \
Vehicle.Body.Trunk.Front.IsLocked \
Vehicle.Body.Trunk.Front.IsOpen \
Vehicle.Body.Trunk.Rear.IsLocked \
Vehicle.Body.Trunk.Rear.IsOpen \
Vehicle.Body.Windshield.Front.IsHeatingOn \
Vehicle.Body.Windshield.Front.WasherFluid.IsLevelLow \
Vehicle.Body.Windshield.Front.WasherFluid.Level \
Vehicle.Body.Windshield.Front.Wiping.Intensity \
Vehicle.Body.Windshield.Front.Wiping.IsWipersWorn \
Vehicle.Body.Windshield.Front.Wiping.Mode \
Vehicle.Body.Windshield.Front.Wiping.System.ActualPosition \
Vehicle.Body.Windshield.Front.Wiping.System.DriveCurrent \
Vehicle.Body.Windshield.Front.Wiping.System.Frequency \
Vehicle.Body.Windshield.Front.Wiping.System.IsBlocked \
Vehicle.Body.Windshield.Front.Wiping.System.IsEndingWipeCycle \
Vehicle.Body.Windshield.Front.Wiping.System.IsOverheated \
Vehicle.Body.Windshield.Front.Wiping.System.IsPositionReached \
Vehicle.Body.Windshield.Front.Wiping.System.IsWiperError \
Vehicle.Body.Windshield.Front.Wiping.System.IsWiping \
Vehicle.Body.Windshield.Front.Wiping.System.Mode \
Vehicle.Body.Windshield.Front.Wiping.System.TargetPosition \
Vehicle.Body.Windshield.Front.Wiping.WiperWear \
Vehicle.Body.Windshield.Rear.IsHeatingOn \
Vehicle.Body.Windshield.Rear.WasherFluid.IsLevelLow \
Vehicle.Body.Windshield.Rear.WasherFluid.Level \
Vehicle.Body.Windshield.Rear.Wiping.Intensity \
Vehicle.Body.Windshield.Rear.Wiping.IsWipersWorn \
Vehicle.Body.Windshield.Rear.Wiping.Mode \
Vehicle.Body.Windshield.Rear.Wiping.System.ActualPosition \
Vehicle.Body.Windshield.Rear.Wiping.System.DriveCurrent \
Vehicle.Body.Windshield.Rear.Wiping.System.Frequency \
Vehicle.Body.Windshield.Rear.Wiping.System.IsBlocked \
Vehicle.Body.Windshield.Rear.Wiping.System.IsEndingWipeCycle \
Vehicle.Body.Windshield.Rear.Wiping.System.IsOverheated \
Vehicle.Body.Windshield.Rear.Wiping.System.IsPositionReached \
Vehicle.Body.Windshield.Rear.Wiping.System.IsWiperError \
Vehicle.Body.Windshield.Rear.Wiping.System.IsWiping \
Vehicle.Body.Windshield.Rear.Wiping.System.Mode \
Vehicle.Body.Windshield.Rear.Wiping.System.TargetPosition \
Vehicle.Body.Windshield.Rear.Wiping.WiperWear \
Vehicle.Cabin.Convertible.Status \
Vehicle.Cabin.Door.Row1.Left.IsChildLockActive \
Vehicle.Cabin.Door.Row1.Left.IsLocked \
Vehicle.Cabin.Door.Row1.Left.IsOpen \
Vehicle.Cabin.Door.Row1.Left.Shade.Position \
Vehicle.Cabin.Door.Row1.Left.Shade.Switch \
Vehicle.Cabin.Door.Row1.Left.Window.IsChildLockEngaged \
Vehicle.Cabin.Door.Row1.Left.Window.IsOpen \
Vehicle.Cabin.Door.Row1.Left.Window.Position \
Vehicle.Cabin.Door.Row1.Left.Window.Switch \
Vehicle.Cabin.Door.Row1.Right.IsChildLockActive \
Vehicle.Cabin.Door.Row1.Right.IsLocked \
Vehicle.Cabin.Door.Row1.Right.IsOpen \
Vehicle.Cabin.Door.Row1.Right.Shade.Position \
Vehicle.Cabin.Door.Row1.Right.Shade.Switch \
Vehicle.Cabin.Door.Row1.Right.Window.IsChildLockEngaged \
Vehicle.Cabin.Door.Row1.Right.Window.IsOpen \
Vehicle.Cabin.Door.Row1.Right.Window.Position \
Vehicle.Cabin.Door.Row1.Right.Window.Switch \
Vehicle.Cabin.Door.Row2.Left.IsChildLockActive \
Vehicle.Cabin.Door.Row2.Left.IsLocked \
Vehicle.Cabin.Door.Row2.Left.IsOpen \
Vehicle.Cabin.Door.Row2.Left.Shade.Position \
Vehicle.Cabin.Door.Row2.Left.Shade.Switch \
Vehicle.Cabin.Door.Row2.Left.Window.IsChildLockEngaged \
Vehicle.Cabin.Door.Row2.Left.Window.IsOpen \
Vehicle.Cabin.Door.Row2.Left.Window.Position \
Vehicle.Cabin.Door.Row2.Left.Window.Switch \
Vehicle.Cabin.Door.Row2.Right.IsChildLockActive \
Vehicle.Cabin.Door.Row2.Right.IsLocked \
Vehicle.Cabin.Door.Row2.Right.IsOpen \
Vehicle.Cabin.Door.Row2.Right.Shade.Position \
Vehicle.Cabin.Door.Row2.Right.Shade.Switch \
Vehicle.Cabin.Door.Row2.Right.Window.IsChildLockEngaged \
Vehicle.Cabin.Door.Row2.Right.Window.IsOpen \
Vehicle.Cabin.Door.Row2.Right.Window.Position \
Vehicle.Cabin.Door.Row2.Right.Window.Switch \
Vehicle.Cabin.DoorCount \
Vehicle.Cabin.DriverPosition \
Vehicle.Cabin.HVAC.AmbientAirTemperature \
Vehicle.Cabin.HVAC.IsAirConditioningActive \
Vehicle.Cabin.HVAC.IsFrontDefrosterActive \
Vehicle.Cabin.HVAC.IsRearDefrosterActive \
Vehicle.Cabin.HVAC.IsRecirculationActive \
Vehicle.Cabin.HVAC.PowerOptimizeLevel \
Vehicle.Cabin.HVAC.Station.Row1.Left.AirDistribution \
Vehicle.Cabin.HVAC.Station.Row1.Left.FanSpeed \
Vehicle.Cabin.HVAC.Station.Row1.Left.Temperature \
Vehicle.Cabin.HVAC.Station.Row1.Right.AirDistribution \
Vehicle.Cabin.HVAC.Station.Row1.Right.FanSpeed \
Vehicle.Cabin.HVAC.Station.Row1.Right.Temperature \
Vehicle.Cabin.HVAC.Station.Row2.Left.AirDistribution \
Vehicle.Cabin.HVAC.Station.Row2.Left.FanSpeed \
Vehicle.Cabin.HVAC.Station.Row2.Left.Temperature \
Vehicle.Cabin.HVAC.Station.Row2.Right.AirDistribution \
Vehicle.Cabin.HVAC.Station.Row2.Right.FanSpeed \
Vehicle.Cabin.HVAC.Station.Row2.Right.Temperature \
Vehicle.Cabin.HVAC.Station.Row3.Left.AirDistribution \
Vehicle.Cabin.HVAC.Station.Row3.Left.FanSpeed \
Vehicle.Cabin.HVAC.Station.Row3.Left.Temperature \
Vehicle.Cabin.HVAC.Station.Row3.Right.AirDistribution \
Vehicle.Cabin.HVAC.Station.Row3.Right.FanSpeed \
Vehicle.Cabin.HVAC.Station.Row3.Right.Temperature \
Vehicle.Cabin.HVAC.Station.Row4.Left.AirDistribution \
Vehicle.Cabin.HVAC.Station.Row4.Left.FanSpeed \
Vehicle.Cabin.HVAC.Station.Row4.Left.Temperature \
Vehicle.Cabin.HVAC.Station.Row4.Right.AirDistribution \
Vehicle.Cabin.HVAC.Station.Row4.Right.FanSpeed \
Vehicle.Cabin.HVAC.Station.Row4.Right.Temperature \
Vehicle.Cabin.Infotainment.HMI.Brightness \
Vehicle.Cabin.Infotainment.HMI.CurrentLanguage \
Vehicle.Cabin.Infotainment.HMI.DateFormat \
Vehicle.Cabin.Infotainment.HMI.DayNightMode \
Vehicle.Cabin.Infotainment.HMI.DistanceUnit \
Vehicle.Cabin.Infotainment.HMI.EVEconomyUnits \
Vehicle.Cabin.Infotainment.HMI.FuelEconomyUnits \
Vehicle.Cabin.Infotainment.HMI.FuelVolumeUnit \
Vehicle.Cabin.Infotainment.HMI.TemperatureUnit \
Vehicle.Cabin.Infotainment.HMI.TimeFormat \
Vehicle.Cabin.Infotainment.HMI.TirePressureUnit \
Vehicle.Cabin.Infotainment.Media.Action \
Vehicle.Cabin.Infotainment.Media.DeclinedURI \
Vehicle.Cabin.Infotainment.Media.Played.Album \
Vehicle.Cabin.Infotainment.Media.Played.Artist \
Vehicle.Cabin.Infotainment.Media.Played.PlaybackRate \
Vehicle.Cabin.Infotainment.Media.Played.Source \
Vehicle.Cabin.Infotainment.Media.Played.Track \
Vehicle.Cabin.Infotainment.Media.Played.URI \
Vehicle.Cabin.Infotainment.Media.SelectedURI \
Vehicle.Cabin.Infotainment.Media.Volume \
Vehicle.Cabin.Infotainment.Navigation.DestinationSet.Latitude \
Vehicle.Cabin.Infotainment.Navigation.DestinationSet.Longitude \
Vehicle.Cabin.Infotainment.Navigation.Mute \
Vehicle.Cabin.Infotainment.Navigation.Volume \
Vehicle.Cabin.Infotainment.PowerOptimizeLevel \
Vehicle.Cabin.Infotainment.SmartphoneProjection.Active \
Vehicle.Cabin.Infotainment.SmartphoneProjection.Source \
Vehicle.Cabin.Infotainment.SmartphoneProjection.SupportedMode \
Vehicle.Cabin.Lights.AmbientLight \
Vehicle.Cabin.Lights.IsDomeOn \
Vehicle.Cabin.Lights.IsGloveBoxOn \
Vehicle.Cabin.Lights.IsTrunkOn \
Vehicle.Cabin.Lights.LightIntensity \
Vehicle.Cabin.Lights.Spotlight.Row1.IsLeftOn \
Vehicle.Cabin.Lights.Spotlight.Row1.IsRightOn \
Vehicle.Cabin.Lights.Spotlight.Row1.IsSharedOn \
Vehicle.Cabin.Lights.Spotlight.Row2.IsLeftOn \
Vehicle.Cabin.Lights.Spotlight.Row2.IsRightOn \
Vehicle.Cabin.Lights.Spotlight.Row2.IsSharedOn \
Vehicle.Cabin.Lights.Spotlight.Row3.IsLeftOn \
Vehicle.Cabin.Lights.Spotlight.Row3.IsRightOn \
Vehicle.Cabin.Lights.Spotlight.Row3.IsSharedOn \
Vehicle.Cabin.Lights.Spotlight.Row4.IsLeftOn \
Vehicle.Cabin.Lights.Spotlight.Row4.IsRightOn \
Vehicle.Cabin.Lights.Spotlight.Row4.IsSharedOn \
Vehicle.Cabin.PowerOptimizeLevel \
Vehicle.Cabin.RearShade.Position \
Vehicle.Cabin.RearShade.Switch \
Vehicle.Cabin.RearviewMirror.DimmingLevel \
Vehicle.Cabin.Seat.Row1.Pos1.Airbag.IsDeployed \
Vehicle.Cabin.Seat.Row1.Pos1.Backrest.Lumbar.Height \
Vehicle.Cabin.Seat.Row1.Pos1.Backrest.Lumbar.Support \
Vehicle.Cabin.Seat.Row1.Pos1.Backrest.Recline \
Vehicle.Cabin.Seat.Row1.Pos1.Backrest.SideBolster.Support \
Vehicle.Cabin.Seat.Row1.Pos1.Headrest.Angle \
Vehicle.Cabin.Seat.Row1.Pos1.Headrest.Height \
Vehicle.Cabin.Seat.Row1.Pos1.Heating \
Vehicle.Cabin.Seat.Row1.Pos1.Height \
Vehicle.Cabin.Seat.Row1.Pos1.IsBelted \
Vehicle.Cabin.Seat.Row1.Pos1.IsOccupied \
Vehicle.Cabin.Seat.Row1.Pos1.Massage \
Vehicle.Cabin.Seat.Row1.Pos1.Occupant.Identifier.Issuer \
Vehicle.Cabin.Seat.Row1.Pos1.Occupant.Identifier.Subject \
Vehicle.Cabin.Seat.Row1.Pos1.Position \
Vehicle.Cabin.Seat.Row1.Pos1.Seating.Length \
Vehicle.Cabin.Seat.Row1.Pos1.Switch.Backrest.IsReclineBackwardEngaged \
Vehicle.Cabin.Seat.Row1.Pos1.Switch.Backrest.IsReclineForwardEngaged \
Vehicle.Cabin.Seat.Row1.Pos1.Switch.Backrest.Lumbar.IsDownEngaged \
Vehicle.Cabin.Seat.Row1.Pos1.Switch.Backrest.Lumbar.IsLessSupportEngaged \
Vehicle.Cabin.Seat.Row1.Pos1.Switch.Backrest.Lumbar.IsMoreSupportEngaged \
Vehicle.Cabin.Seat.Row1.Pos1.Switch.Backrest.Lumbar.IsUpEngaged \
Vehicle.Cabin.Seat.Row1.Pos1.Switch.Backrest.SideBolster.IsLessSupportEngaged \
Vehicle.Cabin.Seat.Row1.Pos1.Switch.Backrest.SideBolster.IsMoreSupportEngaged \
Vehicle.Cabin.Seat.Row1.Pos1.Switch.Headrest.IsBackwardEngaged \
Vehicle.Cabin.Seat.Row1.Pos1.Switch.Headrest.IsDownEngaged \
Vehicle.Cabin.Seat.Row1.Pos1.Switch.Headrest.IsForwardEngaged \
Vehicle.Cabin.Seat.Row1.Pos1.Switch.Headrest.IsUpEngaged \
Vehicle.Cabin.Seat.Row1.Pos1.Switch.IsBackwardEngaged \
Vehicle.Cabin.Seat.Row1.Pos1.Switch.IsCoolerEngaged \
Vehicle.Cabin.Seat.Row1.Pos1.Switch.IsDownEngaged \
Vehicle.Cabin.Seat.Row1.Pos1.Switch.IsForwardEngaged \
Vehicle.Cabin.Seat.Row1.Pos1.Switch.IsTiltBackwardEngaged \
Vehicle.Cabin.Seat.Row1.Pos1.Switch.IsTiltForwardEngaged \
Vehicle.Cabin.Seat.Row1.Pos1.Switch.IsUpEngaged \
Vehicle.Cabin.Seat.Row1.Pos1.Switch.IsWarmerEngaged \
Vehicle.Cabin.Seat.Row1.Pos1.Switch.Massage.IsDecreaseEngaged \
Vehicle.Cabin.Seat.Row1.Pos1.Switch.Massage.IsIncreaseEngaged \
Vehicle.Cabin.Seat.Row1.Pos1.Switch.Seating.IsBackwardEngaged \
Vehicle.Cabin.Seat.Row1.Pos1.Switch.Seating.IsForwardEngaged \
Vehicle.Cabin.Seat.Row1.Pos1.Tilt \
Vehicle.Cabin.Seat.Row1.Pos2.Airbag.IsDeployed \
Vehicle.Cabin.Seat.Row1.Pos2.Backrest.Lumbar.Height \
Vehicle.Cabin.Seat.Row1.Pos2.Backrest.Lumbar.Support \
Vehicle.Cabin.Seat.Row1.Pos2.Backrest.Recline \
Vehicle.Cabin.Seat.Row1.Pos2.Backrest.SideBolster.Support \
Vehicle.Cabin.Seat.Row1.Pos2.Headrest.Angle \
Vehicle.Cabin.Seat.Row1.Pos2.Headrest.Height \
Vehicle.Cabin.Seat.Row1.Pos2.Heating \
Vehicle.Cabin.Seat.Row1.Pos2.Height \
Vehicle.Cabin.Seat.Row1.Pos2.IsBelted \
Vehicle.Cabin.Seat.Row1.Pos2.IsOccupied \
Vehicle.Cabin.Seat.Row1.Pos2.Massage \
Vehicle.Cabin.Seat.Row1.Pos2.Occupant.Identifier.Issuer \
Vehicle.Cabin.Seat.Row1.Pos2.Occupant.Identifier.Subject \
Vehicle.Cabin.Seat.Row1.Pos2.Position \
Vehicle.Cabin.Seat.Row1.Pos2.Seating.Length \
Vehicle.Cabin.Seat.Row1.Pos2.Switch.Backrest.IsReclineBackwardEngaged \
Vehicle.Cabin.Seat.Row1.Pos2.Switch.Backrest.IsReclineForwardEngaged \
Vehicle.Cabin.Seat.Row1.Pos2.Switch.Backrest.Lumbar.IsDownEngaged \
Vehicle.Cabin.Seat.Row1.Pos2.Switch.Backrest.Lumbar.IsLessSupportEngaged \
Vehicle.Cabin.Seat.Row1.Pos2.Switch.Backrest.Lumbar.IsMoreSupportEngaged \
Vehicle.Cabin.Seat.Row1.Pos2.Switch.Backrest.Lumbar.IsUpEngaged \
Vehicle.Cabin.Seat.Row1.Pos2.Switch.Backrest.SideBolster.IsLessSupportEngaged \
Vehicle.Cabin.Seat.Row1.Pos2.Switch.Backrest.SideBolster.IsMoreSupportEngaged \
Vehicle.Cabin.Seat.Row1.Pos2.Switch.Headrest.IsBackwardEngaged \
Vehicle.Cabin.Seat.Row1.Pos2.Switch.Headrest.IsDownEngaged \
Vehicle.Cabin.Seat.Row1.Pos2.Switch.Headrest.IsForwardEngaged \
Vehicle.Cabin.Seat.Row1.Pos2.Switch.Headrest.IsUpEngaged \
Vehicle.Cabin.Seat.Row1.Pos2.Switch.IsBackwardEngaged \
Vehicle.Cabin.Seat.Row1.Pos2.Switch.IsCoolerEngaged \
Vehicle.Cabin.Seat.Row1.Pos2.Switch.IsDownEngaged \
Vehicle.Cabin.Seat.Row1.Pos2.Switch.IsForwardEngaged \
Vehicle.Cabin.Seat.Row1.Pos2.Switch.IsTiltBackwardEngaged \
Vehicle.Cabin.Seat.Row1.Pos2.Switch.IsTiltForwardEngaged \
Vehicle.Cabin.Seat.Row1.Pos2.Switch.IsUpEngaged \
Vehicle.Cabin.Seat.Row1.Pos2.Switch.IsWarmerEngaged \
Vehicle.Cabin.Seat.Row1.Pos2.Switch.Massage.IsDecreaseEngaged \
Vehicle.Cabin.Seat.Row1.Pos2.Switch.Massage.IsIncreaseEngaged \
Vehicle.Cabin.Seat.Row1.Pos2.Switch.Seating.IsBackwardEngaged \
Vehicle.Cabin.Seat.Row1.Pos2.Switch.Seating.IsForwardEngaged \
Vehicle.Cabin.Seat.Row1.Pos2.Tilt \
Vehicle.Cabin.Seat.Row1.Pos3.Airbag.IsDeployed \
Vehicle.Cabin.Seat.Row1.Pos3.Backrest.Lumbar.Height \
Vehicle.Cabin.Seat.Row1.Pos3.Backrest.Lumbar.Support \
Vehicle.Cabin.Seat.Row1.Pos3.Backrest.Recline \
Vehicle.Cabin.Seat.Row1.Pos3.Backrest.SideBolster.Support \
Vehicle.Cabin.Seat.Row1.Pos3.Headrest.Angle \
Vehicle.Cabin.Seat.Row1.Pos3.Headrest.Height \
Vehicle.Cabin.Seat.Row1.Pos3.Heating \
Vehicle.Cabin.Seat.Row1.Pos3.Height \
Vehicle.Cabin.Seat.Row1.Pos3.IsBelted \
Vehicle.Cabin.Seat.Row1.Pos3.IsOccupied \
Vehicle.Cabin.Seat.Row1.Pos3.Massage \
Vehicle.Cabin.Seat.Row1.Pos3.Occupant.Identifier.Issuer \
Vehicle.Cabin.Seat.Row1.Pos3.Occupant.Identifier.Subject \
Vehicle.Cabin.Seat.Row1.Pos3.Position \
Vehicle.Cabin.Seat.Row1.Pos3.Seating.Length \
Vehicle.Cabin.Seat.Row1.Pos3.Switch.Backrest.IsReclineBackwardEngaged \
Vehicle.Cabin.Seat.Row1.Pos3.Switch.Backrest.IsReclineForwardEngaged \
Vehicle.Cabin.Seat.Row1.Pos3.Switch.Backrest.Lumbar.IsDownEngaged \
Vehicle.Cabin.Seat.Row1.Pos3.Switch.Backrest.Lumbar.IsLessSupportEngaged \
Vehicle.Cabin.Seat.Row1.Pos3.Switch.Backrest.Lumbar.IsMoreSupportEngaged \
Vehicle.Cabin.Seat.Row1.Pos3.Switch.Backrest.Lumbar.IsUpEngaged \
Vehicle.Cabin.Seat.Row1.Pos3.Switch.Backrest.SideBolster.IsLessSupportEngaged \
Vehicle.Cabin.Seat.Row1.Pos3.Switch.Backrest.SideBolster.IsMoreSupportEngaged \
Vehicle.Cabin.Seat.Row1.Pos3.Switch.Headrest.IsBackwardEngaged \
Vehicle.Cabin.Seat.Row1.Pos3.Switch.Headrest.IsDownEngaged \
Vehicle.Cabin.Seat.Row1.Pos3.Switch.Headrest.IsForwardEngaged \
Vehicle.Cabin.Seat.Row1.Pos3.Switch.Headrest.IsUpEngaged \
Vehicle.Cabin.Seat.Row1.Pos3.Switch.IsBackwardEngaged \
Vehicle.Cabin.Seat.Row1.Pos3.Switch.IsCoolerEngaged \
Vehicle.Cabin.Seat.Row1.Pos3.Switch.IsDownEngaged \
Vehicle.Cabin.Seat.Row1.Pos3.Switch.IsForwardEngaged \
Vehicle.Cabin.Seat.Row1.Pos3.Switch.IsTiltBackwardEngaged \
Vehicle.Cabin.Seat.Row1.Pos3.Switch.IsTiltForwardEngaged \
Vehicle.Cabin.Seat.Row1.Pos3.Switch.IsUpEngaged \
Vehicle.Cabin.Seat.Row1.Pos3.Switch.IsWarmerEngaged \
Vehicle.Cabin.Seat.Row1.Pos3.Switch.Massage.IsDecreaseEngaged \
Vehicle.Cabin.Seat.Row1.Pos3.Switch.Massage.IsIncreaseEngaged \
Vehicle.Cabin.Seat.Row1.Pos3.Switch.Seating.IsBackwardEngaged \
Vehicle.Cabin.Seat.Row1.Pos3.Switch.Seating.IsForwardEngaged \
Vehicle.Cabin.Seat.Row1.Pos3.Tilt \
Vehicle.Cabin.Seat.Row2.Pos1.Airbag.IsDeployed \
Vehicle.Cabin.Seat.Row2.Pos1.Backrest.Lumbar.Height \
Vehicle.Cabin.Seat.Row2.Pos1.Backrest.Lumbar.Support \
Vehicle.Cabin.Seat.Row2.Pos1.Backrest.Recline \
Vehicle.Cabin.Seat.Row2.Pos1.Backrest.SideBolster.Support \
Vehicle.Cabin.Seat.Row2.Pos1.Headrest.Angle \
Vehicle.Cabin.Seat.Row2.Pos1.Headrest.Height \
Vehicle.Cabin.Seat.Row2.Pos1.Heating \
Vehicle.Cabin.Seat.Row2.Pos1.Height \
Vehicle.Cabin.Seat.Row2.Pos1.IsBelted \
Vehicle.Cabin.Seat.Row2.Pos1.IsOccupied \
Vehicle.Cabin.Seat.Row2.Pos1.Massage \
Vehicle.Cabin.Seat.Row2.Pos1.Occupant.Identifier.Issuer \
Vehicle.Cabin.Seat.Row2.Pos1.Occupant.Identifier.Subject \
Vehicle.Cabin.Seat.Row2.Pos1.Position \
Vehicle.Cabin.Seat.Row2.Pos1.Seating.Length \
Vehicle.Cabin.Seat.Row2.Pos1.Switch.Backrest.IsReclineBackwardEngaged \
Vehicle.Cabin.Seat.Row2.Pos1.Switch.Backrest.IsReclineForwardEngaged \
Vehicle.Cabin.Seat.Row2.Pos1.Switch.Backrest.Lumbar.IsDownEngaged \
Vehicle.Cabin.Seat.Row2.Pos1.Switch.Backrest.Lumbar.IsLessSupportEngaged \
Vehicle.Cabin.Seat.Row2.Pos1.Switch.Backrest.Lumbar.IsMoreSupportEngaged \
Vehicle.Cabin.Seat.Row2.Pos1.Switch.Backrest.Lumbar.IsUpEngaged \
Vehicle.Cabin.Seat.Row2.Pos1.Switch.Backrest.SideBolster.IsLessSupportEngaged \
Vehicle.Cabin.Seat.Row2.Pos1.Switch.Backrest.SideBolster.IsMoreSupportEngaged \
Vehicle.Cabin.Seat.Row2.Pos1.Switch.Headrest.IsBackwardEngaged \
Vehicle.Cabin.Seat.Row2.Pos1.Switch.Headrest.IsDownEngaged \
Vehicle.Cabin.Seat.Row2.Pos1.Switch.Headrest.IsForwardEngaged \
Vehicle.Cabin.Seat.Row2.Pos1.Switch.Headrest.IsUpEngaged \
Vehicle.Cabin.Seat.Row2.Pos1.Switch.IsBackwardEngaged \
Vehicle.Cabin.Seat.Row2.Pos1.Switch.IsCoolerEngaged \
Vehicle.Cabin.Seat.Row2.Pos1.Switch.IsDownEngaged \
Vehicle.Cabin.Seat.Row2.Pos1.Switch.IsForwardEngaged \
Vehicle.Cabin.Seat.Row2.Pos1.Switch.IsTiltBackwardEngaged \
Vehicle.Cabin.Seat.Row2.Pos1.Switch.IsTiltForwardEngaged \
Vehicle.Cabin.Seat.Row2.Pos1.Switch.IsUpEngaged \
Vehicle.Cabin.Seat.Row2.Pos1.Switch.IsWarmerEngaged \
Vehicle.Cabin.Seat.Row2.Pos1.Switch.Massage.IsDecreaseEngaged \
Vehicle.Cabin.Seat.Row2.Pos1.Switch.Massage.IsIncreaseEngaged \
Vehicle.Cabin.Seat.Row2.Pos1.Switch.Seating.IsBackwardEngaged \
Vehicle.Cabin.Seat.Row2.Pos1.Switch.Seating.IsForwardEngaged \
Vehicle.Cabin.Seat.Row2.Pos1.Tilt \
Vehicle.Cabin.Seat.Row2.Pos2.Airbag.IsDeployed \
Vehicle.Cabin.Seat.Row2.Pos2.Backrest.Lumbar.Height \
Vehicle.Cabin.Seat.Row2.Pos2.Backrest.Lumbar.Support \
Vehicle.Cabin.Seat.Row2.Pos2.Backrest.Recline \
Vehicle.Cabin.Seat.Row2.Pos2.Backrest.SideBolster.Support \
Vehicle.Cabin.Seat.Row2.Pos2.Headrest.Angle \
Vehicle.Cabin.Seat.Row2.Pos2.Headrest.Height \
Vehicle.Cabin.Seat.Row2.Pos2.Heating \
Vehicle.Cabin.Seat.Row2.Pos2.Height \
Vehicle.Cabin.Seat.Row2.Pos2.IsBelted \
Vehicle.Cabin.Seat.Row2.Pos2.IsOccupied \
Vehicle.Cabin.Seat.Row2.Pos2.Massage \
Vehicle.Cabin.Seat.Row2.Pos2.Occupant.Identifier.Issuer \
Vehicle.Cabin.Seat.Row2.Pos2.Occupant.Identifier.Subject \
Vehicle.Cabin.Seat.Row2.Pos2.Position \
Vehicle.Cabin.Seat.Row2.Pos2.Seating.Length \
Vehicle.Cabin.Seat.Row2.Pos2.Switch.Backrest.IsReclineBackwardEngaged \
Vehicle.Cabin.Seat.Row2.Pos2.Switch.Backrest.IsReclineForwardEngaged \
Vehicle.Cabin.Seat.Row2.Pos2.Switch.Backrest.Lumbar.IsDownEngaged \
Vehicle.Cabin.Seat.Row2.Pos2.Switch.Backrest.Lumbar.IsLessSupportEngaged \
Vehicle.Cabin.Seat.Row2.Pos2.Switch.Backrest.Lumbar.IsMoreSupportEngaged \
Vehicle.Cabin.Seat.Row2.Pos2.Switch.Backrest.Lumbar.IsUpEngaged \
Vehicle.Cabin.Seat.Row2.Pos2.Switch.Backrest.SideBolster.IsLessSupportEngaged \
Vehicle.Cabin.Seat.Row2.Pos2.Switch.Backrest.SideBolster.IsMoreSupportEngaged \
Vehicle.Cabin.Seat.Row2.Pos2.Switch.Headrest.IsBackwardEngaged \
Vehicle.Cabin.Seat.Row2.Pos2.Switch.Headrest.IsDownEngaged \
Vehicle.Cabin.Seat.Row2.Pos2.Switch.Headrest.IsForwardEngaged \
Vehicle.Cabin.Seat.Row2.Pos2.Switch.Headrest.IsUpEngaged \
Vehicle.Cabin.Seat.Row2.Pos2.Switch.IsBackwardEngaged \
Vehicle.Cabin.Seat.Row2.Pos2.Switch.IsCoolerEngaged \
Vehicle.Cabin.Seat.Row2.Pos2.Switch.IsDownEngaged \
Vehicle.Cabin.Seat.Row2.Pos2.Switch.IsForwardEngaged \
Vehicle.Cabin.Seat.Row2.Pos2.Switch.IsTiltBackwardEngaged \
Vehicle.Cabin.Seat.Row2.Pos2.Switch.IsTiltForwardEngaged \
Vehicle.Cabin.Seat.Row2.Pos2.Switch.IsUpEngaged \
Vehicle.Cabin.Seat.Row2.Pos2.Switch.IsWarmerEngaged \
Vehicle.Cabin.Seat.Row2.Pos2.Switch.Massage.IsDecreaseEngaged \
Vehicle.Cabin.Seat.Row2.Pos2.Switch.Massage.IsIncreaseEngaged \
Vehicle.Cabin.Seat.Row2.Pos2.Switch.Seating.IsBackwardEngaged \
Vehicle.Cabin.Seat.Row2.Pos2.Switch.Seating.IsForwardEngaged \
Vehicle.Cabin.Seat.Row2.Pos2.Tilt \
Vehicle.Cabin.Seat.Row2.Pos3.Airbag.IsDeployed \
Vehicle.Cabin.Seat.Row2.Pos3.Backrest.Lumbar.Height \
Vehicle.Cabin.Seat.Row2.Pos3.Backrest.Lumbar.Support \
Vehicle.Cabin.Seat.Row2.Pos3.Backrest.Recline \
Vehicle.Cabin.Seat.Row2.Pos3.Backrest.SideBolster.Support \
Vehicle.Cabin.Seat.Row2.Pos3.Headrest.Angle \
Vehicle.Cabin.Seat.Row2.Pos3.Headrest.Height \
Vehicle.Cabin.Seat.Row2.Pos3.Heating \
Vehicle.Cabin.Seat.Row2.Pos3.Height \
Vehicle.Cabin.Seat.Row2.Pos3.IsBelted \
Vehicle.Cabin.Seat.Row2.Pos3.IsOccupied \
Vehicle.Cabin.Seat.Row2.Pos3.Massage \
Vehicle.Cabin.Seat.Row2.Pos3.Occupant.Identifier.Issuer \
Vehicle.Cabin.Seat.Row2.Pos3.Occupant.Identifier.Subject \
Vehicle.Cabin.Seat.Row2.Pos3.Position \
Vehicle.Cabin.Seat.Row2.Pos3.Seating.Length \
Vehicle.Cabin.Seat.Row2.Pos3.Switch.Backrest.IsReclineBackwardEngaged \
Vehicle.Cabin.Seat.Row2.Pos3.Switch.Backrest.IsReclineForwardEngaged \
Vehicle.Cabin.Seat.Row2.Pos3.Switch.Backrest.Lumbar.IsDownEngaged \
Vehicle.Cabin.Seat.Row2.Pos3.Switch.Backrest.Lumbar.IsLessSupportEngaged \
Vehicle.Cabin.Seat.Row2.Pos3.Switch.Backrest.Lumbar.IsMoreSupportEngaged \
Vehicle.Cabin.Seat.Row2.Pos3.Switch.Backrest.Lumbar.IsUpEngaged \
Vehicle.Cabin.Seat.Row2.Pos3.Switch.Backrest.SideBolster.IsLessSupportEngaged \
Vehicle.Cabin.Seat.Row2.Pos3.Switch.Backrest.SideBolster.IsMoreSupportEngaged \
Vehicle.Cabin.Seat.Row2.Pos3.Switch.Headrest.IsBackwardEngaged \
Vehicle.Cabin.Seat.Row2.Pos3.Switch.Headrest.IsDownEngaged \
Vehicle.Cabin.Seat.Row2.Pos3.Switch.Headrest.IsForwardEngaged \
Vehicle.Cabin.Seat.Row2.Pos3.Switch.Headrest.IsUpEngaged \
Vehicle.Cabin.Seat.Row2.Pos3.Switch.IsBackwardEngaged \
Vehicle.Cabin.Seat.Row2.Pos3.Switch.IsCoolerEngaged \
Vehicle.Cabin.Seat.Row2.Pos3.Switch.IsDownEngaged \
Vehicle.Cabin.Seat.Row2.Pos3.Switch.IsForwardEngaged \
Vehicle.Cabin.Seat.Row2.Pos3.Switch.IsTiltBackwardEngaged \
Vehicle.Cabin.Seat.Row2.Pos3.Switch.IsTiltForwardEngaged \
Vehicle.Cabin.Seat.Row2.Pos3.Switch.IsUpEngaged \
Vehicle.Cabin.Seat.Row2.Pos3.Switch.IsWarmerEngaged \
Vehicle.Cabin.Seat.Row2.Pos3.Switch.Massage.IsDecreaseEngaged \
Vehicle.Cabin.Seat.Row2.Pos3.Switch.Massage.IsIncreaseEngaged \
Vehicle.Cabin.Seat.Row2.Pos3.Switch.Seating.IsBackwardEngaged \
Vehicle.Cabin.Seat.Row2.Pos3.Switch.Seating.IsForwardEngaged \
Vehicle.Cabin.Seat.Row2.Pos3.Tilt \
Vehicle.Cabin.SeatPosCount \
Vehicle.Cabin.SeatRowCount \
Vehicle.Cabin.Sunroof.Position \
Vehicle.Cabin.Sunroof.Shade.Position \
Vehicle.Cabin.Sunroof.Shade.Switch \
Vehicle.Cabin.Sunroof.Switch \
Vehicle.CargoVolume \
Vehicle.Chassis.Accelerator.PedalPosition \
Vehicle.Chassis.Axle.Row1.SteeringAngle \
Vehicle.Chassis.Axle.Row1.TireAspectRatio \
Vehicle.Chassis.Axle.Row1.TireDiameter \
Vehicle.Chassis.Axle.Row1.TireWidth \
Vehicle.Chassis.Axle.Row1.TyreLocation \
Vehicle.Chassis.Axle.Row1.VerticalLoad \
Vehicle.Chassis.Axle.Row1.Wheel.Left.Brake.FluidLevel \
Vehicle.Chassis.Axle.Row1.Wheel.Left.Brake.IsBrakesWorn \
Vehicle.Chassis.Axle.Row1.Wheel.Left.Brake.IsFluidLevelLow \
Vehicle.Chassis.Axle.Row1.Wheel.Left.Brake.PadWear \
Vehicle.Chassis.Axle.Row1.Wheel.Left.Speed \
Vehicle.Chassis.Axle.Row1.Wheel.Left.Tire.IsPressureLow \
Vehicle.Chassis.Axle.Row1.Wheel.Left.Tire.Pressure \
Vehicle.Chassis.Axle.Row1.Wheel.Left.Tire.Temperature \
Vehicle.Chassis.Axle.Row1.Wheel.Right.Brake.FluidLevel \
Vehicle.Chassis.Axle.Row1.Wheel.Right.Brake.IsBrakesWorn \
Vehicle.Chassis.Axle.Row1.Wheel.Right.Brake.IsFluidLevelLow \
Vehicle.Chassis.Axle.Row1.Wheel.Right.Brake.PadWear \
Vehicle.Chassis.Axle.Row1.Wheel.Right.Speed \
Vehicle.Chassis.Axle.Row1.Wheel.Right.Tire.IsPressureLow \
Vehicle.Chassis.Axle.Row1.Wheel.Right.Tire.Pressure \
Vehicle.Chassis.Axle.Row1.Wheel.Right.Tire.Temperature \
Vehicle.Chassis.Axle.Row1.WheelCount \
Vehicle.Chassis.Axle.Row1.WheelDiameter \
Vehicle.Chassis.Axle.Row1.WheelWidth \
Vehicle.Chassis.Axle.Row2.SteeringAngle \
Vehicle.Chassis.Axle.Row2.TireAspectRatio \
Vehicle.Chassis.Axle.Row2.TireDiameter \
Vehicle.Chassis.Axle.Row2.TireWidth \
Vehicle.Chassis.Axle.Row2.TyreLocation \
Vehicle.Chassis.Axle.Row2.VerticalLoad \
Vehicle.Chassis.Axle.Row2.Wheel.Left.Brake.FluidLevel \
Vehicle.Chassis.Axle.Row2.Wheel.Left.Brake.IsBrakesWorn \
Vehicle.Chassis.Axle.Row2.Wheel.Left.Brake.IsFluidLevelLow \
Vehicle.Chassis.Axle.Row2.Wheel.Left.Brake.PadWear \
Vehicle.Chassis.Axle.Row2.Wheel.Left.Speed \
Vehicle.Chassis.Axle.Row2.Wheel.Left.Tire.IsPressureLow \
Vehicle.Chassis.Axle.Row2.Wheel.Left.Tire.Pressure \
Vehicle.Chassis.Axle.Row2.Wheel.Left.Tire.Temperature \
Vehicle.Chassis.Axle.Row2.Wheel.Right.Brake.FluidLevel \
Vehicle.Chassis.Axle.Row2.Wheel.Right.Brake.IsBrakesWorn \
Vehicle.Chassis.Axle.Row2.Wheel.Right.Brake.IsFluidLevelLow \
Vehicle.Chassis.Axle.Row2.Wheel.Right.Brake.PadWear \
Vehicle.Chassis.Axle.Row2.Wheel.Right.Speed \
Vehicle.Chassis.Axle.Row2.Wheel.Right.Tire.IsPressureLow \
Vehicle.Chassis.Axle.Row2.Wheel.Right.Tire.Pressure \
Vehicle.Chassis.Axle.Row2.Wheel.Right.Tire.Temperature \
Vehicle.Chassis.Axle.Row2.WheelCount \
Vehicle.Chassis.Axle.Row2.WheelDiameter \
Vehicle.Chassis.Axle.Row2.WheelWidth \
Vehicle.Chassis.Axle.Row3.TyreLocation \
Vehicle.Chassis.Axle.Row3.VerticalLoad \
Vehicle.Chassis.Axle.Row4.TyreLocation \
Vehicle.Chassis.Axle.Row4.VerticalLoad \
Vehicle.Chassis.Axle.Row5.TyreLocation \
Vehicle.Chassis.Axle.Row5.VerticalLoad \
Vehicle.Chassis.Axle.Row6.TyreLocation \
Vehicle.Chassis.Axle.Row6.VerticalLoad \
Vehicle.Chassis.AxleCount \
Vehicle.Chassis.Brake.IsDriverEmergencyBrakingDetected \
Vehicle.Chassis.Brake.PedalPosition \
Vehicle.Chassis.ParkingBrake.IsEngaged \
Vehicle.Chassis.SteeringWheel.Angle \
Vehicle.Chassis.SteeringWheel.Extension \
Vehicle.Chassis.SteeringWheel.Position \
Vehicle.Chassis.SteeringWheel.Tilt \
Vehicle.Chassis.Track \
Vehicle.Chassis.Wheelbase \
Vehicle.CombinedVehicleWeight \
Vehicle.Connectivity.IsConnectivityAvailable \
Vehicle.CurbWeight \
Vehicle.CurrentLocation.Altitude \
Vehicle.CurrentLocation.GNSSReceiver.FixType \
Vehicle.CurrentLocation.GNSSReceiver.MountingPosition.X \
Vehicle.CurrentLocation.GNSSReceiver.MountingPosition.Y \
Vehicle.CurrentLocation.GNSSReceiver.MountingPosition.Z \
Vehicle.CurrentLocation.Heading \
Vehicle.CurrentLocation.HorizontalAccuracy \
Vehicle.CurrentLocation.Latitude \
Vehicle.CurrentLocation.Longitude \
Vehicle.CurrentLocation.Speed \
Vehicle.CurrentLocation.Timestamp \
Vehicle.CurrentLocation.VerticalAccuracy \
Vehicle.CurrentOverallWeight \
Vehicle.DirectionIndicator \
Vehicle.Driver.AttentiveProbability \
Vehicle.Driver.DistractionLevel \
Vehicle.Driver.FatigueLevel \
Vehicle.Driver.HeartRate \
Vehicle.Driver.Identifier.Issuer \
Vehicle.Driver.Identifier.Subject \
Vehicle.Driver.IsEyesOnRoad \
Vehicle.EmissionsCO2 \
Vehicle.Exterior.AirTemperature \
Vehicle.Exterior.Humidity \
Vehicle.Exterior.LightIntensity \
Vehicle.GrossWeight \
Vehicle.Height \
Vehicle.IsBrokenDown \
Vehicle.IsMoving \
Vehicle.IsOverspeed \
Vehicle.Length \
Vehicle.LowVoltageBattery.CurrentCurrent \
Vehicle.LowVoltageBattery.CurrentVoltage \
Vehicle.LowVoltageBattery.NominalCapacity \
Vehicle.LowVoltageBattery.NominalVoltage \
Vehicle.LowVoltageSystemState \
Vehicle.MaxTowBallWeight \
Vehicle.MaxTowWeight \
Vehicle.OBD.AbsoluteLoad \
Vehicle.OBD.AcceleratorPositionD \
Vehicle.OBD.AcceleratorPositionE \
Vehicle.OBD.AcceleratorPositionF \
Vehicle.OBD.AirStatus \
Vehicle.OBD.AmbientAirTemperature \
Vehicle.OBD.BarometricPressure \
Vehicle.OBD.Catalyst.Bank1.Temperature1 \
Vehicle.OBD.Catalyst.Bank1.Temperature2 \
Vehicle.OBD.Catalyst.Bank2.Temperature1 \
Vehicle.OBD.Catalyst.Bank2.Temperature2 \
Vehicle.OBD.CommandedEGR \
Vehicle.OBD.CommandedEVAP \
Vehicle.OBD.CommandedEquivalenceRatio \
Vehicle.OBD.ControlModuleVoltage \
Vehicle.OBD.CoolantTemperature \
Vehicle.OBD.DTCList \
Vehicle.OBD.DistanceSinceDTCClear \
Vehicle.OBD.DistanceWithMIL \
Vehicle.OBD.DriveCycleStatus.DTCCount \
Vehicle.OBD.DriveCycleStatus.IgnitionType \
Vehicle.OBD.DriveCycleStatus.IsMILOn \
Vehicle.OBD.EGRError \
Vehicle.OBD.EVAPVaporPressure \
Vehicle.OBD.EVAPVaporPressureAbsolute \
Vehicle.OBD.EVAPVaporPressureAlternate \
Vehicle.OBD.EngineLoad \
Vehicle.OBD.EngineSpeed \
Vehicle.OBD.EthanolPercent \
Vehicle.OBD.FreezeDTC \
Vehicle.OBD.FuelInjectionTiming \
Vehicle.OBD.FuelLevel \
Vehicle.OBD.FuelPressure \
Vehicle.OBD.FuelRailPressureAbsolute \
Vehicle.OBD.FuelRailPressureDirect \
Vehicle.OBD.FuelRailPressureVac \
Vehicle.OBD.FuelRate \
Vehicle.OBD.FuelStatus \
Vehicle.OBD.FuelType \
Vehicle.OBD.HybridBatteryRemaining \
Vehicle.OBD.IntakeTemp \
Vehicle.OBD.IsPTOActive \
Vehicle.OBD.LongTermFuelTrim1 \
Vehicle.OBD.LongTermFuelTrim2 \
Vehicle.OBD.LongTermO2Trim1 \
Vehicle.OBD.LongTermO2Trim2 \
Vehicle.OBD.LongTermO2Trim3 \
Vehicle.OBD.LongTermO2Trim4 \
Vehicle.OBD.MAF \
Vehicle.OBD.MAP \
Vehicle.OBD.MaxMAF \
Vehicle.OBD.O2.Sensor1.ShortTermFuelTrim \
Vehicle.OBD.O2.Sensor1.Voltage \
Vehicle.OBD.O2.Sensor2.ShortTermFuelTrim \
Vehicle.OBD.O2.Sensor2.Voltage \
Vehicle.OBD.O2.Sensor3.ShortTermFuelTrim \
Vehicle.OBD.O2.Sensor3.Voltage \
Vehicle.OBD.O2.Sensor4.ShortTermFuelTrim \
Vehicle.OBD.O2.Sensor4.Voltage \
Vehicle.OBD.O2.Sensor5.ShortTermFuelTrim \
Vehicle.OBD.O2.Sensor5.Voltage \
Vehicle.OBD.O2.Sensor6.ShortTermFuelTrim \
Vehicle.OBD.O2.Sensor6.Voltage \
Vehicle.OBD.O2.Sensor7.ShortTermFuelTrim \
Vehicle.OBD.O2.Sensor7.Voltage \
Vehicle.OBD.O2.Sensor8.ShortTermFuelTrim \
Vehicle.OBD.O2.Sensor8.Voltage \
Vehicle.OBD.O2WR.Sensor1.Current \
Vehicle.OBD.O2WR.Sensor1.Lambda \
Vehicle.OBD.O2WR.Sensor1.Voltage \
Vehicle.OBD.O2WR.Sensor2.Current \
Vehicle.OBD.O2WR.Sensor2.Lambda \
Vehicle.OBD.O2WR.Sensor2.Voltage \
Vehicle.OBD.O2WR.Sensor3.Current \
Vehicle.OBD.O2WR.Sensor3.Lambda \
Vehicle.OBD.O2WR.Sensor3.Voltage \
Vehicle.OBD.O2WR.Sensor4.Current \
Vehicle.OBD.O2WR.Sensor4.Lambda \
Vehicle.OBD.O2WR.Sensor4.Voltage \
Vehicle.OBD.O2WR.Sensor5.Current \
Vehicle.OBD.O2WR.Sensor5.Lambda \
Vehicle.OBD.O2WR.Sensor5.Voltage \
Vehicle.OBD.O2WR.Sensor6.Current \
Vehicle.OBD.O2WR.Sensor6.Lambda \
Vehicle.OBD.O2WR.Sensor6.Voltage \
Vehicle.OBD.O2WR.Sensor7.Current \
Vehicle.OBD.O2WR.Sensor7.Lambda \
Vehicle.OBD.O2WR.Sensor7.Voltage \
Vehicle.OBD.O2WR.Sensor8.Current \
Vehicle.OBD.O2WR.Sensor8.Lambda \
Vehicle.OBD.O2WR.Sensor8.Voltage \
Vehicle.OBD.OBDStandards \
Vehicle.OBD.OilTemperature \
Vehicle.OBD.OxygenSensorsIn2Banks \
Vehicle.OBD.OxygenSensorsIn4Banks \
Vehicle.OBD.PidsA \
Vehicle.OBD.PidsB \
Vehicle.OBD.PidsC \
Vehicle.OBD.RelativeAcceleratorPosition \
Vehicle.OBD.RelativeThrottlePosition \
Vehicle.OBD.RunTime \
Vehicle.OBD.RunTimeMIL \
Vehicle.OBD.ShortTermFuelTrim1 \
Vehicle.OBD.ShortTermFuelTrim2 \
Vehicle.OBD.ShortTermO2Trim1 \
Vehicle.OBD.ShortTermO2Trim2 \
Vehicle.OBD.ShortTermO2Trim3 \
Vehicle.OBD.ShortTermO2Trim4 \
Vehicle.OBD.Speed \
Vehicle.OBD.Status.DTCCount \
Vehicle.OBD.Status.IgnitionType \
Vehicle.OBD.Status.IsMILOn \
Vehicle.OBD.ThrottleActuator \
Vehicle.OBD.ThrottlePosition \
Vehicle.OBD.ThrottlePositionB \
Vehicle.OBD.ThrottlePositionC \
Vehicle.OBD.TimeSinceDTCCleared \
Vehicle.OBD.TimingAdvance \
Vehicle.OBD.WarmupsSinceDTCClear \
Vehicle.PowerOptimizeLevel \
Vehicle.Powertrain.AccumulatedBrakingEnergy \
Vehicle.Powertrain.Brake.ActualRetarderPercentage \
Vehicle.Powertrain.CombustionEngine.ActualEnginePercentTorque \
Vehicle.Powertrain.CombustionEngine.AspirationType \
Vehicle.Powertrain.CombustionEngine.Bore \
Vehicle.Powertrain.CombustionEngine.CompressionRatio \
Vehicle.Powertrain.CombustionEngine.Configuration \
Vehicle.Powertrain.CombustionEngine.DieselExhaustFluid.Capacity \
Vehicle.Powertrain.CombustionEngine.DieselExhaustFluid.IsLevelLow \
Vehicle.Powertrain.CombustionEngine.DieselExhaustFluid.Level \
Vehicle.Powertrain.CombustionEngine.DieselExhaustFluid.Range \
Vehicle.Powertrain.CombustionEngine.DieselParticulateFilter.DeltaPressure \
Vehicle.Powertrain.CombustionEngine.DieselParticulateFilter.InletTemperature \
Vehicle.Powertrain.CombustionEngine.DieselParticulateFilter.OutletTemperature \
Vehicle.Powertrain.CombustionEngine.Displacement \
Vehicle.Powertrain.CombustionEngine.ECT \
Vehicle.Powertrain.CombustionEngine.EOP \
Vehicle.Powertrain.CombustionEngine.EOT \
Vehicle.Powertrain.CombustionEngine.EngineCode \
Vehicle.Powertrain.CombustionEngine.EngineCoolantCapacity \
Vehicle.Powertrain.CombustionEngine.EngineHours \
Vehicle.Powertrain.CombustionEngine.EngineOilCapacity \
Vehicle.Powertrain.CombustionEngine.EngineOilLevel \
Vehicle.Powertrain.CombustionEngine.IdleHours \
Vehicle.Powertrain.CombustionEngine.IsRunning \
Vehicle.Powertrain.CombustionEngine.MAF \
Vehicle.Powertrain.CombustionEngine.MAP \
Vehicle.Powertrain.CombustionEngine.MaxPower \
Vehicle.Powertrain.CombustionEngine.MaxTorque \
Vehicle.Powertrain.CombustionEngine.NumberOfCylinders \
Vehicle.Powertrain.CombustionEngine.NumberOfValvesPerCylinder \
Vehicle.Powertrain.CombustionEngine.OilLifeRemaining \
Vehicle.Powertrain.CombustionEngine.Power \
Vehicle.Powertrain.CombustionEngine.Speed \
Vehicle.Powertrain.CombustionEngine.StrokeLength \
Vehicle.Powertrain.CombustionEngine.TPS \
Vehicle.Powertrain.CombustionEngine.Torque \
Vehicle.Powertrain.CurrentFuelType \
Vehicle.Powertrain.Eec2AcceleratorPedalPosition \
Vehicle.Powertrain.Eec2EnginePercentLoad \
Vehicle.Powertrain.ElectricMotor.CoolantTemperature \
Vehicle.Powertrain.ElectricMotor.EngineCode \
Vehicle.Powertrain.ElectricMotor.MaxPower \
Vehicle.Powertrain.ElectricMotor.MaxRegenPower \
Vehicle.Powertrain.ElectricMotor.MaxRegenTorque \
Vehicle.Powertrain.ElectricMotor.MaxTorque \
Vehicle.Powertrain.ElectricMotor.MotorHours \
Vehicle.Powertrain.ElectricMotor.Power \
Vehicle.Powertrain.ElectricMotor.Speed \
Vehicle.Powertrain.ElectricMotor.Temperature \
Vehicle.Powertrain.ElectricMotor.Torque \
Vehicle.Powertrain.FuelSystem.AccumulatedConsumption \
Vehicle.Powertrain.FuelSystem.AverageConsumption \
Vehicle.Powertrain.FuelSystem.ConsumptionSinceStart \
Vehicle.Powertrain.FuelSystem.HybridType \
Vehicle.Powertrain.FuelSystem.InstantConsumption \
Vehicle.Powertrain.FuelSystem.IsEngineStopStartEnabled \
Vehicle.Powertrain.FuelSystem.IsFuelLevelLow \
Vehicle.Powertrain.FuelSystem.Level \
Vehicle.Powertrain.FuelSystem.Range \
Vehicle.Powertrain.FuelSystem.SupportedFuel \
Vehicle.Powertrain.FuelSystem.SupportedFuelTypes \
Vehicle.Powertrain.FuelSystem.Tank.First.Fuel \
Vehicle.Powertrain.FuelSystem.Tank.First.RelativeLevel \
Vehicle.Powertrain.FuelSystem.Tank.Second.Fuel \
Vehicle.Powertrain.FuelSystem.Tank.Second.RelativeLevel \
Vehicle.Powertrain.FuelSystem.TankCapacity \
Vehicle.Powertrain.FuelSystem.TimeSinceStart \
Vehicle.Powertrain.PTODriveEngagement \
Vehicle.Powertrain.PowerOptimizeLevel \
Vehicle.Powertrain.Range \
Vehicle.Powertrain.TractionBattery.AccumulatedChargedEnergy \
Vehicle.Powertrain.TractionBattery.AccumulatedChargedThroughput \
Vehicle.Powertrain.TractionBattery.AccumulatedConsumedEnergy \
Vehicle.Powertrain.TractionBattery.AccumulatedConsumedThroughput \
Vehicle.Powertrain.TractionBattery.Charging.ChargeCurrent.DC \
Vehicle.Powertrain.TractionBattery.Charging.ChargeCurrent.Phase1 \
Vehicle.Powertrain.TractionBattery.Charging.ChargeCurrent.Phase2 \
Vehicle.Powertrain.TractionBattery.Charging.ChargeCurrent.Phase3 \
Vehicle.Powertrain.TractionBattery.Charging.ChargeLimit \
Vehicle.Powertrain.TractionBattery.Charging.ChargePlugType \
Vehicle.Powertrain.TractionBattery.Charging.ChargePortFlap \
Vehicle.Powertrain.TractionBattery.Charging.ChargeRate \
Vehicle.Powertrain.TractionBattery.Charging.ChargeVoltage.DC \
Vehicle.Powertrain.TractionBattery.Charging.ChargeVoltage.Phase1 \
Vehicle.Powertrain.TractionBattery.Charging.ChargeVoltage.Phase2 \
Vehicle.Powertrain.TractionBattery.Charging.ChargeVoltage.Phase3 \
Vehicle.Powertrain.TractionBattery.Charging.IsCharging \
Vehicle.Powertrain.TractionBattery.Charging.IsChargingCableConnected \
Vehicle.Powertrain.TractionBattery.Charging.IsChargingCableLocked \
Vehicle.Powertrain.TractionBattery.Charging.IsDischarging \
Vehicle.Powertrain.TractionBattery.Charging.MaximumChargingCurrent.DC \
Vehicle.Powertrain.TractionBattery.Charging.MaximumChargingCurrent.Phase1 \
Vehicle.Powertrain.TractionBattery.Charging.MaximumChargingCurrent.Phase2 \
Vehicle.Powertrain.TractionBattery.Charging.MaximumChargingCurrent.Phase3 \
Vehicle.Powertrain.TractionBattery.Charging.Mode \
Vehicle.Powertrain.TractionBattery.Charging.PowerLoss \
Vehicle.Powertrain.TractionBattery.Charging.StartStopCharging \
Vehicle.Powertrain.TractionBattery.Charging.Temperature \
Vehicle.Powertrain.TractionBattery.Charging.TimeToComplete \
Vehicle.Powertrain.TractionBattery.Charging.Timer.Mode \
Vehicle.Powertrain.TractionBattery.Charging.Timer.Time \
Vehicle.Powertrain.TractionBattery.CoolantTemperature \
Vehicle.Powertrain.TractionBattery.CurrentCurrent \
Vehicle.Powertrain.TractionBattery.CurrentPower \
Vehicle.Powertrain.TractionBattery.CurrentVoltage \
Vehicle.Powertrain.TractionBattery.DCDC.PowerLoss \
Vehicle.Powertrain.TractionBattery.DCDC.Temperature \
Vehicle.Powertrain.TractionBattery.GrossCapacity \
Vehicle.Powertrain.TractionBattery.Id \
Vehicle.Powertrain.TractionBattery.IsGroundConnected \
Vehicle.Powertrain.TractionBattery.IsPowerConnected \
Vehicle.Powertrain.TractionBattery.MaxVoltage \
Vehicle.Powertrain.TractionBattery.NetCapacity \
Vehicle.Powertrain.TractionBattery.NominalVoltage \
Vehicle.Powertrain.TractionBattery.PowerLoss \
Vehicle.Powertrain.TractionBattery.ProductionDate \
Vehicle.Powertrain.TractionBattery.Range \
Vehicle.Powertrain.TractionBattery.StateOfCharge.Current \
Vehicle.Powertrain.TractionBattery.StateOfCharge.Displayed \
Vehicle.Powertrain.TractionBattery.StateOfHealth \
Vehicle.Powertrain.TractionBattery.Temperature.Average \
Vehicle.Powertrain.TractionBattery.Temperature.Max \
Vehicle.Powertrain.TractionBattery.Temperature.Min \
Vehicle.Powertrain.Transmission.ClutchEngagement \
Vehicle.Powertrain.Transmission.ClutchWear \
Vehicle.Powertrain.Transmission.CurrentGear \
Vehicle.Powertrain.Transmission.DiffLockFrontEngagement \
Vehicle.Powertrain.Transmission.DiffLockRearEngagement \
Vehicle.Powertrain.Transmission.DriveType \
Vehicle.Powertrain.Transmission.GearChangeMode \
Vehicle.Powertrain.Transmission.GearCount \
Vehicle.Powertrain.Transmission.IsElectricalPowertrainEngaged \
Vehicle.Powertrain.Transmission.IsLowRangeEngaged \
Vehicle.Powertrain.Transmission.IsParkLockEngaged \
Vehicle.Powertrain.Transmission.PerformanceMode \
Vehicle.Powertrain.Transmission.SelectedGear \
Vehicle.Powertrain.Transmission.Temperature \
Vehicle.Powertrain.Transmission.TorqueDistribution \
Vehicle.Powertrain.Transmission.TravelledDistance \
Vehicle.Powertrain.Transmission.Type \
Vehicle.Powertrain.Type \
Vehicle.RoofLoad \
Vehicle.Service.DistanceToService \
Vehicle.Service.IsServiceDue \
Vehicle.Service.TimeToService \
Vehicle.Speed \
Vehicle.StartTime \
Vehicle.Tachograph.Driver.Driver1.AuthenticationEquipment \
Vehicle.Tachograph.Driver.Driver1.CardIssuingMemberState \
Vehicle.Tachograph.Driver.Driver1.CardRenewalIndex \
Vehicle.Tachograph.Driver.Driver1.CardReplacementIndex \
Vehicle.Tachograph.Driver.Driver1.Identification \
Vehicle.Tachograph.Driver.Driver1.IsCardPresent \
Vehicle.Tachograph.Driver.Driver1.IsLoggedIn \
Vehicle.Tachograph.Driver.Driver1.OemIdentification \
Vehicle.Tachograph.Driver.Driver1.OemIdentificationType \
Vehicle.Tachograph.Driver.Driver1.TimeRelatedStatus \
Vehicle.Tachograph.Driver.Driver1.WorkingState \
Vehicle.Tachograph.Driver.Driver2.AuthenticationEquipment \
Vehicle.Tachograph.Driver.Driver2.CardIssuingMemberState \
Vehicle.Tachograph.Driver.Driver2.CardRenewalIndex \
Vehicle.Tachograph.Driver.Driver2.CardReplacementIndex \
Vehicle.Tachograph.Driver.Driver2.Identification \
Vehicle.Tachograph.Driver.Driver2.IsCardPresent \
Vehicle.Tachograph.Driver.Driver2.IsLoggedIn \
Vehicle.Tachograph.Driver.Driver2.OemIdentification \
Vehicle.Tachograph.Driver.Driver2.OemIdentificationType \
Vehicle.Tachograph.Driver.Driver2.TimeRelatedStatus \
Vehicle.Tachograph.Driver.Driver2.WorkingState \
Vehicle.Tachograph.HandlingInformation \
Vehicle.Tachograph.Performance \
Vehicle.Tachograph.SystemEvent \
Vehicle.Tachograph.VehicleSpeed \
Vehicle.Trailer.IsConnected \
Vehicle.TraveledDistance \
Vehicle.TraveledDistanceHighRes \
Vehicle.TraveledDistanceSinceStart \
Vehicle.TripDuration \
Vehicle.TripMeterReading \
Vehicle.VehicleIdentification.AcrissCode \
Vehicle.VehicleIdentification.BodyType \
Vehicle.VehicleIdentification.Brand \
Vehicle.VehicleIdentification.DateVehicleFirstRegistered \
Vehicle.VehicleIdentification.KnownVehicleDamages \
Vehicle.VehicleIdentification.MeetsEmissionStandard \
Vehicle.VehicleIdentification.Model \
Vehicle.VehicleIdentification.OptionalExtras \
Vehicle.VehicleIdentification.ProductionDate \
Vehicle.VehicleIdentification.PurchaseDate \
Vehicle.VehicleIdentification.VIN \
Vehicle.VehicleIdentification.VehicleConfiguration \
Vehicle.VehicleIdentification.VehicleInteriorColor \
Vehicle.VehicleIdentification.VehicleInteriorType \
Vehicle.VehicleIdentification.VehicleModelDate \
Vehicle.VehicleIdentification.VehicleSeatingCapacity \
Vehicle.VehicleIdentification.VehicleSpecialUsage \
Vehicle.VehicleIdentification.WMI \
Vehicle.VehicleIdentification.Year \
Vehicle.VersionVSS.Label \
Vehicle.VersionVSS.Major \
Vehicle.VersionVSS.Minor \
Vehicle.VersionVSS.Patch \
Vehicle.Width
